# Generated by Django 2.1.15 on 2023-06-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dostawcy',
            fields=[
                ('iddostawcy', models.IntegerField(db_column='IDdostawcy', primary_key=True, serialize=False)),
                ('nazwafirmy', models.CharField(db_column='NazwaFirmy', max_length=40)),
                ('przedstawiciel', models.CharField(blank=True, db_column='Przedstawiciel', max_length=30, null=True)),
                ('stanowiskoprzedstawiciela', models.CharField(blank=True, db_column='StanowiskoPrzedstawiciela', max_length=30, null=True)),
                ('adres', models.CharField(blank=True, db_column='Adres', max_length=60, null=True)),
                ('miasto', models.CharField(blank=True, db_column='Miasto', max_length=15, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=15, null=True)),
                ('kodpocztowy', models.CharField(blank=True, db_column='KodPocztowy', max_length=10, null=True)),
                ('kraj', models.CharField(blank=True, db_column='Kraj', max_length=15, null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=24, null=True)),
                ('faks', models.CharField(blank=True, db_column='Faks', max_length=24, null=True)),
                ('stronamacierzysta', models.TextField(blank=True, db_column='StronaMacierzysta', null=True)),
            ],
            options={
                'db_table': 'Dostawcy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('idkategorii', models.IntegerField(db_column='IDkategorii', primary_key=True, serialize=False)),
                ('nazwakategorii', models.CharField(db_column='NazwaKategorii', max_length=20)),
                ('opis', models.TextField(blank=True, db_column='Opis', null=True)),
                ('rysunek', models.BinaryField(blank=True, db_column='Rysunek', null=True)),
            ],
            options={
                'db_table': 'Kategorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klienci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idklienta', models.CharField(blank=True, db_column='IDklienta', max_length=5, null=True)),
                ('nazwafirmy', models.CharField(db_column='NazwaFirmy', max_length=40)),
                ('przedstawiciel', models.CharField(blank=True, db_column='Przedstawiciel', max_length=30, null=True)),
                ('stanowiskoprzedstawiciela', models.CharField(blank=True, db_column='StanowiskoPrzedstawiciela', max_length=35, null=True)),
                ('adres', models.CharField(blank=True, db_column='Adres', max_length=60, null=True)),
                ('miasto', models.CharField(blank=True, db_column='Miasto', max_length=15, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=15, null=True)),
                ('kodpocztowy', models.CharField(blank=True, db_column='KodPocztowy', max_length=10, null=True)),
                ('kraj', models.CharField(blank=True, db_column='Kraj', max_length=15, null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=24, null=True)),
                ('faks', models.CharField(blank=True, db_column='Faks', max_length=24, null=True)),
            ],
            options={
                'db_table': 'Klienci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pozycjezamwienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idzamówienia', models.IntegerField(blank=True, db_column='IDzamówienia', null=True)),
                ('idproduktu', models.IntegerField(db_column='IDproduktu')),
                ('cenajednostkowa', models.DecimalField(db_column='CenaJednostkowa', decimal_places=4, max_digits=19)),
                ('ilość', models.SmallIntegerField(db_column='Ilość')),
                ('rabat', models.FloatField(db_column='Rabat')),
            ],
            options={
                'db_table': 'PozycjeZamówienia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpracownika', models.IntegerField(db_column='IDpracownika')),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=20)),
                ('imię', models.CharField(db_column='Imię', max_length=10)),
                ('stanowisko', models.CharField(blank=True, db_column='Stanowisko', max_length=40, null=True)),
                ('zwrotgrzecznościowy', models.CharField(blank=True, db_column='ZwrotGrzecznościowy', max_length=25, null=True)),
                ('dataurodzenia', models.DateTimeField(blank=True, db_column='DataUrodzenia', null=True)),
                ('datazatrudnienia', models.DateTimeField(blank=True, db_column='DataZatrudnienia', null=True)),
                ('adres', models.CharField(blank=True, db_column='Adres', max_length=60, null=True)),
                ('miasto', models.CharField(blank=True, db_column='Miasto', max_length=15, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=15, null=True)),
                ('kodpocztowy', models.CharField(blank=True, db_column='KodPocztowy', max_length=10, null=True)),
                ('kraj', models.CharField(blank=True, db_column='Kraj', max_length=15, null=True)),
                ('telefondomowy', models.CharField(blank=True, db_column='TelefonDomowy', max_length=24, null=True)),
                ('telefonwewnętrzny', models.CharField(blank=True, db_column='TelefonWewnętrzny', max_length=4, null=True)),
                ('fotografia', models.BinaryField(blank=True, db_column='Fotografia', null=True)),
                ('uwagi', models.TextField(blank=True, db_column='Uwagi', null=True)),
                ('szef', models.IntegerField(blank=True, db_column='Szef', null=True)),
            ],
            options={
                'db_table': 'Pracownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproduktu', models.IntegerField(db_column='IDproduktu')),
                ('nazwaproduktu', models.CharField(db_column='NazwaProduktu', max_length=40)),
                ('iddostawcy', models.IntegerField(blank=True, db_column='IDdostawcy', null=True)),
                ('idkategorii', models.IntegerField(blank=True, db_column='IDkategorii', null=True)),
                ('ilośćjednostkowa', models.CharField(blank=True, db_column='IlośćJednostkowa', max_length=255, null=True)),
                ('cenajednostkowa', models.DecimalField(blank=True, db_column='CenaJednostkowa', decimal_places=4, max_digits=19, null=True)),
                ('stanmagazynu', models.SmallIntegerField(blank=True, db_column='StanMagazynu', null=True)),
                ('ilośćzamówiona', models.SmallIntegerField(blank=True, db_column='IlośćZamówiona', null=True)),
                ('stanminimum', models.SmallIntegerField(blank=True, db_column='StanMinimum', null=True)),
                ('wycofany', models.BooleanField(db_column='Wycofany')),
            ],
            options={
                'db_table': 'Produkty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spedytorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idspedytora', models.IntegerField(db_column='IDspedytora')),
                ('nazwafirmy', models.CharField(db_column='NazwaFirmy', max_length=40)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=24, null=True)),
            ],
            options={
                'db_table': 'Spedytorzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zamwienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idzamówienia', models.IntegerField(db_column='IDzamówienia')),
                ('idklienta', models.CharField(db_column='IDklienta', max_length=5)),
                ('idpracownika', models.IntegerField(blank=True, db_column='IDpracownika', null=True)),
                ('datazamówienia', models.DateTimeField(blank=True, db_column='DataZamówienia', null=True)),
                ('datawymagana', models.DateTimeField(blank=True, db_column='DataWymagana', null=True)),
                ('datawysyłki', models.DateTimeField(blank=True, db_column='DataWysyłki', null=True)),
                ('idspedytora', models.IntegerField(blank=True, db_column='IDspedytora', null=True)),
                ('fracht', models.DecimalField(blank=True, db_column='Fracht', decimal_places=4, max_digits=19, null=True)),
                ('nazwaodbiorcy', models.CharField(blank=True, db_column='NazwaOdbiorcy', max_length=40, null=True)),
                ('adresodbiorcy', models.CharField(blank=True, db_column='AdresOdbiorcy', max_length=60, null=True)),
                ('miastoodbiorcy', models.CharField(blank=True, db_column='MiastoOdbiorcy', max_length=15, null=True)),
                ('regionodbiorcy', models.CharField(blank=True, db_column='RegionOdbiorcy', max_length=15, null=True)),
                ('kodpocztowyodbiorcy', models.CharField(blank=True, db_column='KodPocztowyOdbiorcy', max_length=10, null=True)),
                ('krajodbiorcy', models.CharField(blank=True, db_column='KrajOdbiorcy', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Zamówienia',
                'managed': False,
            },
        ),
    ]
