# Generated by Django 2.1.15 on 2023-06-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozycjezamówienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idzamówienia', models.IntegerField(blank=True, db_column='IDzamówienia', null=True)),
                ('idproduktu', models.IntegerField(db_column='IDproduktu')),
                ('cenajednostkowa', models.DecimalField(db_column='CenaJednostkowa', decimal_places=4, max_digits=19)),
                ('ilość', models.SmallIntegerField(db_column='Ilość')),
                ('rabat', models.FloatField(db_column='Rabat')),
            ],
            options={
                'db_table': 'PozycjeZamówienia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zamówienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idzamówienia', models.IntegerField(db_column='IDzamówienia')),
                ('idklienta', models.CharField(db_column='IDklienta', max_length=5)),
                ('idpracownika', models.IntegerField(blank=True, db_column='IDpracownika', null=True)),
                ('datazamówienia', models.DateTimeField(blank=True, db_column='DataZamówienia', null=True)),
                ('datawymagana', models.DateTimeField(blank=True, db_column='DataWymagana', null=True)),
                ('datawysyłki', models.DateTimeField(blank=True, db_column='DataWysyłki', null=True)),
                ('idspedytora', models.IntegerField(blank=True, db_column='IDspedytora', null=True)),
                ('fracht', models.DecimalField(blank=True, db_column='Fracht', decimal_places=4, max_digits=19, null=True)),
                ('nazwaodbiorcy', models.CharField(blank=True, db_column='NazwaOdbiorcy', max_length=40, null=True)),
                ('adresodbiorcy', models.CharField(blank=True, db_column='AdresOdbiorcy', max_length=60, null=True)),
                ('miastoodbiorcy', models.CharField(blank=True, db_column='MiastoOdbiorcy', max_length=15, null=True)),
                ('regionodbiorcy', models.CharField(blank=True, db_column='RegionOdbiorcy', max_length=15, null=True)),
                ('kodpocztowyodbiorcy', models.CharField(blank=True, db_column='KodPocztowyOdbiorcy', max_length=10, null=True)),
                ('krajodbiorcy', models.CharField(blank=True, db_column='KrajOdbiorcy', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Zamówienia',
                'managed': False,
            },
        ),
    ]
